from enum import Enum
class SignalDirection(Enum):
    STRONG_BULLISH = "STRONG BULLISH"
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    BEARISH = "BEARISH"
    STRONG_BEARISH = "STRONG BEARISH"

class MarketStructure(Enum):
    TREND_CONTINUATION = "TREND_CONTINUATION"
    TREND_REVERSAL = "TREND_REVERSAL"
    RANGE_BOUND = "RANGE_BOUND"
    BREAKOUT = "BREAKOUT"
    BREAKDOWN = "BREAKDOWN"
